// RootLayoutServer.tsx
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "RGIS KL",
  description: "Generated by create next app",
};

const font = DM_Sans({
  subsets: ['latin'],
  weight: ['400','500','600','700'],
  variable: "--font-dm-sans",
});

export default function RootLayoutServer({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
